name: Lint
on: 
  push:
    paths:
      - src/*
jobs: 
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i -g eslint
    - name: Lint files
      run: eslint src --ext .js